services:
  grayhat_csharp_ch2:
    container_name: grayhat_csharp_ch2
    hostname: grayhat_csharp_ch2
    image: sierrahackingco/grayhat_csharp_ch2:latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      custom_net:
    restart: unless-stopped

  bad_store:
    container_name: bad_store
    hostname: bad_store
    image: jvhoof/badstore-docker
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      - grayhat_csharp_ch2
    networks:
      custom_net:
        ipv4_address: 10.5.0.5

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1